name: "Documentation"
description: "Report missing or unclear documentation."
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Please describe the documentation issue you are reporting.

  - type: input
    id: summary
    attributes:
      label: "Summary"
      description: "Briefly describe the documentation issue."
      placeholder: "The documentation for..."
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "Details"
      description: "Provide context on what is missing or unclear."
      placeholder: "The documentation could be improved by..."
