name: Feature Request
description: Suggest a new feature or improvement for the template
title: '[Feature]: '
labels: ['enhancement']
assignees: []
body:
  - type: markdown
    attributes:
      value: Please provide detailed information about the proposed feature or improvement.

  - type: checkboxes
    id: terms
    attributes:
      label: Preflight Checklist
      description: Please ensure these steps have been completed before submitting
      options:
        - label: I have searched existing issues to ensure this feature hasn't already been requested
          required: true
        - label: I have checked the documentation and README
          required: true
        - label: This feature would benefit the template for multiple use cases (not just my specific project)
          required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: What would you like to be able to do?
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the pain point or limitation you're experiencing
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution in detail
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
      placeholder: Describe any alternative solutions or workarounds you've thought about

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of improvement is this?
      options:
        - New package or tool integration
        - Development experience improvement
        - Build/CI/CD enhancement
        - Documentation improvement
        - Configuration/setup improvement
        - Performance optimization
        - Developer tooling
        - Other
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: What are some specific scenarios where this feature would be useful?
      placeholder: |
        1. When developing...
        2. When deploying...
        3. When configuring...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here
      placeholder: Links to similar implementations, mockups, code examples, etc.
