name: Question or Support
description: Ask a question about using the template
title: '[Question]: '
labels: ['question']
assignees: []
body:
  - type: markdown
    attributes:
      value: Please provide as much context as possible to ensure an effective response.

  - type: checkboxes
    id: terms
    attributes:
      label: Preflight Checklist
      description: Please ensure these steps have been completed before asking
      options:
        - label: I have searched existing issues and discussions for similar questions
          required: true
        - label: I have checked the documentation and README
          required: true
        - label: I have tried the suggested troubleshooting steps (if applicable)
          required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please be as specific as possible about what you're trying to accomplish
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you trying to achieve?
      placeholder: Describe your use case, what you're building, or what you're trying to configure
    validations:
      required: true

  - type: textarea
    id: attempted-solutions
    attributes:
      label: What Have You Tried?
      description: What approaches have you already attempted?
      placeholder: List the steps you've taken or solutions you've tried

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: Please provide information about your environment if it might be relevant
      placeholder: |
        - OS: [e.g. macOS 14.0, Windows 11, Ubuntu 22.04]
        - Node.js version: [e.g. 18.17.0]
        - PNPM version: [e.g. 8.6.0]
        - Browser (if applicable): [e.g. Chrome 118, Firefox 119]
      render: markdown

  - type: textarea
    id: code-example
    attributes:
      label: Code Example (if applicable)
      description: Share any relevant code that might help us understand your question
      placeholder: Paste any relevant configuration, code snippets, or error messages
      render: shell

  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What category does your question fall into?
      options:
        - Setup and installation
        - Configuration
        - Development workflow
        - Build and deployment
        - Testing
        - Turborepo usage
        - Package management
        - Integration with other tools
        - Best practices
        - Troubleshooting
        - Other
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context that might be helpful
      placeholder: Screenshots, links to related resources, etc.
