#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running lint-staged for apps..."
pnpm --filter web exec lint-staged
pnpm --filter web-e2e exec lint-staged

echo "Running lint-staged for packages..."
pnpm --filter @repo/shared exec lint-staged
