name: Commitlint

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate commit messages
        uses: wagoid/commitlint-github-action@v6