name: Publish

on:
  push:
    tags: ['*-v*']

permissions:
  contents: write
  packages: write

jobs:
  publish:
    uses: andrewdyer/react-vite-turborepo-workflows/.github/workflows/publish.yml@main
    with:
      tag: ${{ github.ref_name }}
      scope: '@${{ github.repository_owner }}'
      dispatch-deploy: true
    secrets:
      packages-token: ${{ secrets.PACKAGES_TOKEN }}
