name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: andrewdyer/react-vite-turborepo-workflows/.github/workflows/release.yml@main
    secrets:
      release-please-token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
