name: Test

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

concurrency:
  group: test-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  test:
    if: ${{ !startsWith(github.head_ref, 'release-please--') }}
    uses: andrewdyer/react-vite-turborepo-workflows/.github/workflows/test.yml@main
    with:
      scope: '@${{ github.repository_owner }}'
    secrets:
      packages-token: ${{ secrets.PACKAGES_TOKEN }}
